
//! Autogenerated weights for `tightly_coupling_pallet`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 49.0.0
//! DATE: 2025-11-26, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `MacBookPro13`, CPU: `<UNKNOWN>`
//! WASM-EXECUTION: `Compiled`, CHAIN: `None`, DB CACHE: `1024`

// Executed Command:
// frame-omni-bencher
// v1
// benchmark
// pallet
// --runtime
// target/release/wbuild/parachain-template-runtime/parachain_template_runtime.compact.compressed.wasm
// --pallet
// tightly_coupling_pallet
// --extrinsic
// 
// --template
// ./pallets/benchmarking/frame-umbrella-weight-template.hbs
// --output
// ./pallets/tightly-coupling/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::weights_prelude::*;

/// Weight functions needed for `tightly_coupling_pallet`.
pub trait WeightInfo {
	fn access_on_chain_pallet_template() -> Weight;
	fn update_on_chain_pallet_template() -> Weight;
}

/// Weights for `tightly_coupling_pallet` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `TemplatePallet::Something` (r:1 w:0)
	/// Proof: `TemplatePallet::Something` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn access_on_chain_pallet_template() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31`
		//  Estimated: `1489`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(23_000_000, 1489)
			.saturating_add(T::DbWeight::get().reads(1_u64))
	}
	/// Storage: `TemplatePallet::Something` (r:0 w:1)
	/// Proof: `TemplatePallet::Something` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_on_chain_pallet_template() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	/// Storage: `TemplatePallet::Something` (r:1 w:0)
	/// Proof: `TemplatePallet::Something` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn access_on_chain_pallet_template() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `31`
		//  Estimated: `1489`
		// Minimum execution time: 11_000_000 picoseconds.
		Weight::from_parts(23_000_000, 1489)
			.saturating_add(RocksDbWeight::get().reads(1_u64))
	}
	/// Storage: `TemplatePallet::Something` (r:0 w:1)
	/// Proof: `TemplatePallet::Something` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
	fn update_on_chain_pallet_template() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 6_000_000 picoseconds.
		Weight::from_parts(16_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
}
